### ISSUE TITLE
About interpolate unvoiced

### ISSUE THREAD

**Issue by huutuongtu** [interactiveaudiolab/penn#21]
Sorry, I have some questions: 
Firstly, Is it possible to turn off the interpolation for unvoiced frames? I noticed that some unvoiced frames still have f0 value greater than 0. I also tried changing the "interp_unvoiced_at" hyperparameter to 0, 1, or None, but it still didn't work. 
Secondly, is there any way to load the model first and then make predictions? Your penn.from_audio interface seems time-consuming. 
Apologies for not diving deep into your code, so I'm not entirely sure. Thank you

For example:
output from pyworld:
```
array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
       214.00394634, 228.41550318, 231.02428818, 226.94287334,
       224.22705603, 222.11641763, 235.59165735, 245.18583285,
       255.40681954, 249.87755371,   0.        ,   0.        ])
```
output from the model:
```
array([100.42597, 100.43951, 100.43832, 100.43585, 100.44038, 100.43616,
       100.45066, 216.45068, 227.6709 , 230.09619, 229.59361, 225.0241 ,
       222.8692 , 222.2856 , 239.04639, 245.06598, 252.09511, 251.54546,
       280.79706, 394.68484],)
```

Edit: I have checked the code and recognize that the F0 in unvoiced frames being non-zero is not caused by interpolation, but rather by the model's prediction. Is this behavior correct?

**Comment by maxrmorrison** [comment]
The model gets cached on the first call and is not reloaded on subsequent calls unless you change the device or checkpoint.

`interp_unvoiced_at` interpolates when periodicity is below the threshold. 0 and 1 are the max and min of periodicity, so it doesn't make sense to set the threshold to either of those. Try 0.1625, which is reported as optimal in the paper.

As with almost all statistical pitch estimators (and most DSP estimators), the model does not natively predict zeros. Those zeros are a postprocessing step. Estimators that give zeros are throwing out unrecoverable information on the voiced/unvoiced probability. If you want zeros for unvoiced, you manually do that by thresholding the periodicity. That's why periodicity is always returned as well. Note by making unvoiced zero, you are throwing away information by making voiced/unvoiced binary instead of keeping it continuous as in the periodicity contour. Better to keep pitch and periodicity continuous and threshold only when needed (e.g., for evaluation).

**Comment by AznamirWoW** [comment]
Okay, using the pitch and periodicity the same way as with torchcrepe, the comparison results are


![Image](https://github.com/user-attachments/assets/43635fc4-9e82-4cf2-91d0-2211565474c0)
